"""Base data model

Revision ID: 76da901ce787
Revises: 
Create Date: 2022-04-09 02:00:02.584563

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '76da901ce787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_id'), 'zone', ['id'], unique=False)
    op.create_table('activity',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('recurrence_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.create_table('planting',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planting_id'), 'planting', ['id'], unique=False)
    op.drop_index('ix_plant_id', table_name='plant')
    op.drop_index('ix_plant_name', table_name='plant')
    op.drop_table('plant')
    op.add_column('garden', sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('garden', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.drop_index('ix_garden_name', table_name='garden')
    op.create_foreign_key(None, 'garden', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'garden', 'zone', ['zone_id'], ['id'])
    op.alter_column('species', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_species_id', table_name='species')
    op.drop_index('ix_species_name', table_name='species')
    op.drop_index('ix_species_owner_id', table_name='species')
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_user_full_name', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.create_index('ix_species_owner_id', 'species', ['owner_id'], unique=False)
    op.create_index('ix_species_name', 'species', ['name'], unique=False)
    op.create_index('ix_species_id', 'species', ['id'], unique=False)
    op.alter_column('species', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'garden', type_='foreignkey')
    op.drop_constraint(None, 'garden', type_='foreignkey')
    op.create_index('ix_garden_name', 'garden', ['name'], unique=False)
    op.drop_column('garden', 'zone_id')
    op.drop_column('garden', 'owner_id')
    op.create_table('plant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='plant_pkey')
    )
    op.create_index('ix_plant_name', 'plant', ['name'], unique=False)
    op.create_index('ix_plant_id', 'plant', ['id'], unique=False)
    op.drop_index(op.f('ix_planting_id'), table_name='planting')
    op.drop_table('planting')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_zone_id'), table_name='zone')
    op.drop_table('zone')
    # ### end Alembic commands ###
